name: Playwright Tests with Reusable Workflow
on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment to run tests against"
        type: string
        required: false
jobs:
  call-template-tests:
    uses: karwatmateusz/Playwright-template/.github/workflows/reusable-test.yml@master
    with:
      caller-repo: ${{ github.repository }}
      pr-number: 0
