name: Playwright Tests with Reusable Workflow
on:
  pull_request:
    branches: [main, master]
  workflow_dispatch:
    # This workflow is triggered on pull requests to the main or master branch and can also be manually dispatched.
    inputs:
      env:
        description: "Environment to run tests against"
        type: string
        required: false

jobs:
  test:
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      envsec: ${{ steps.npm-cache-dir.outputs.envsec }}
      envir: ${{ env.envir}}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: |
          exit 0
          echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
          echo "envir=skip" >> $GITHUB_ENV
          echo "ENVSEC=skip" >> $GITHUB_OUTPUT
          echo "set to skip"
          echo "$ENVSEC"

      - name: view the secrets context
        shell: bash
        run: |
          echo "$SECRETS_CONTEXT"
          echo "${{ github.event.pull_request.number }}"
          echo "ENVSEC=${{ env.envir }}" >> $GITHUB_OUTPUT
          echo "envir from env: $envir"
        env:
          SECRETS_CONTEXT: ${{ toJson(secrets) }}

  dispatch:
    if: ${{ !cancelled() }}
    needs: test
    outputs:
      envsec: ${{ needs.test.outputs.envsec }}
      envir: ${{ steps.env-setup.outputs.envir }}
    runs-on: ubuntu-latest
    steps:
      - name: echo environment
        id: env-setup
        shell: bash
        run: |
          echo "Running tests against environment: ${{ github.event.inputs.env }}"
          echo "envir=${{ inputs.env }}" >> $GITHUB_OUTPUT

  call-template-tests:
    if: ${{ !cancelled() }}
    needs: [dispatch]
    # permissions:
    #   issues: write
    #   pull-requests: write
    # uses: karwatmateusz/Playwright-template/.github/workflows/reusable-test.yml@master
    # with:
    #   caller-repo: ${{ github.repository }}
    #   pr-number: ${{ github.event.pull_request.number }}
    # secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - name: Skip
        run: |
          echo "Checking if the workflow was skipped"
          if [[ "${{ needs.dispatch.outputs.envir }}" == "skip" ]]; then
            echo "Skipping the workflow call as envir is set to skip"
            exit 0
          else
            echo "envir is not set to skip, proceeding with the workflow call"
          fi
      - name: Call reusable workflow
        run: |
          echo "${{ toJson(needs.dispatch.outputs) }}"
