name: Playwright Tests with Reusable Workflow
on:
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:
  # This workflow is triggered on pull requests to the main or master branch and can also be manually dispatched.
    inputs:
      env: 
        description: 'Environment to run tests against'
        required: false

jobs:
  test:
    if: ${{ github.event_name == 'pull_request' }}
    timeout-minutes: 60
    runs-on: ubuntu-latest
    outputs:
      envsec: ${{ env.ENVSEC }}
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
    
    - name: Get npm cache directory
      id: npm-cache-dir
      shell: bash
      run: | 
        echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}
        echo "ENVSEC=skip" >> $GITHUB_OUTPUT
        echo "ENVSEC=skip" >> $GITHUB_ENV
        echo "set to skip"
        echo "$ENVSEC"
    
    - uses: actions/cache@v3
      id: npm-cache
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
    
    - name: Cache Playwright browsers
      uses: actions/cache@v3
      id: playwright-cache
      with:
        path: ~/.cache/ms-playwright
        key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-playwright-
    
    - name: Install dependencies
      run: npm ci


    - name: view the secrets context
      shell: bash
      run: |
        echo "$SECRETS_CONTEXT"
        echo "${{ github.event.pull_request.number}}"
      env:
        SECRETS_CONTEXT: ${{ toJson(secrets) }}
    
    - name: Install Playwright Browsers
      if: steps.playwright-cache.outputs.cache-hit != 'true'
      run: npx playwright install --with-deps chromium
    
    - name: Run Playwright tests
      run: npx playwright test
    
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30

  dispatch:
    if: ${{ github.event_name == 'workflow_dispatch' }}
    runs-on: ubuntu-latest
    steps:
      - name: echo environment
        run: |
          echo "Running tests against environment: ${{ github.event.inputs.env }}"

  call-template-tests:
    if: ${{ always() }}
    needs: [test, dispatch]
    # permissions:
    #   issues: write
    #   pull-requests: write
    # uses: karwatmateusz/Playwright-template/.github/workflows/reusable-test.yml@master
    # with:
    #   caller-repo: ${{ github.repository }}
    #   pr-number: ${{ github.event.pull_request.number }}
    # secrets: inherit
    runs-on: ubuntu-latest
    steps:
      - name: Something
        run: |
          echo "Checking if the workflow was called"
          if [[ "${{ needs.test.outputs.envsec }}" == "skip" ]]; then
            echo "Skipping the workflow call as ENVSEC is set to skip"
            exit 0
          else
            echo "ENVSEC is not set to skip, proceeding with the workflow call"
          fi